-- definir una funcion
-- justificarCentro :: Int -> String -> String
-- de forma que justificarCentro n st son devuelva un String de longitud n en el
-- cual se han agregado espacios en ambos extremos de st de modo que quede centrado
-- Validar todos los casos
-- dar una solucioin utilizando la clausula where y otra sin ella.